#!/usr/bin/env bash
# Bash script that configures a new machine for Ubuntu
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R ubuntu /var/www
echo "Hello World" > /var/www/html/index.nginx-debian.html
service nginx start