#!/usr/bin/env bash
# Using your debugging skill
# Nginx installation from listening to port 80
# Bash script with the minimum number of commands
# automate your fix.

sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
